name: R-run-models1

on:
  schedule:
    - cron: '0 0 2 1,4,7,10 *'
  push:
    paths:
      - 'code/01_calculate_indices.R'

jobs:
  run-models:
    runs-on: macos-latest
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: Rscript -e "install.packages(c('remotes', 'dplyr', 'future', 'future.apply', 'sdmTMB', 'stringr', 'lubridate'))"

      - name: Install indexwc
        run: Rscript -e "remotes::install_github('pfmc-assessments/indexwc')"

      - name: Install nwfscSurvey
        run: Rscript -e "remotes::install_github('pfmc-assessments/nwfscSurvey')"

      - name: Run SDMs with sdmTMB for Batch ${{ matrix.batch }}
        run: Rscript code/01_calculate_indices.R ${{ matrix.batch }}

      - name: Upload results for Batch ${{ matrix.batch }}
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch }}
          path: |
            output/
            diagnostics/

  commit-results:
    runs-on: macos-latest
    needs: run-models
    steps:
      - uses: actions/checkout@v4

      - name: Download all batch outputs
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Move results into repo
        run: |
          mkdir -p output diagnostics
          find artifacts -type f -name '*.rds' -exec cp {} output/ \;
          find artifacts -type f -name '*.png' -exec cp {} diagnostics/ \;

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output/ diagnostics/  # Only stage output and diagnostics
          # Confirm nothing else (like .github/workflows/) is accidentally staged
          git status
          git diff --cached --name-only | grep '^.github/' && echo "Skipping commit due to workflow file change" && exit 0
          git diff-index --quiet HEAD || (git commit -m '[bot] update files' && git push)
