commit-results:
    runs-on: macos-latest
    needs: run-models
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to create and switch branches

      - name: Download all batch outputs
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create clean branch with only results
        run: |
          git checkout --orphan autogen-results
          git rm -rf . || true  # remove everything from the index
          mkdir -p output diagnostics
          find artifacts -type f -name '*.rds' -exec cp {} output/ \;
          find artifacts -type f -name '*.png' -exec cp {} diagnostics/ \;
          git add output/ diagnostics/
          git commit -m "[bot] update results for all batches"

      - name: Push to autogen-results branch
        env:
          PAT_PUSH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -f https://x-access-token:${PAT_PUSH}@github.com/${{ github.repository }}.git autogen-results
